import { execFile } from "node:child_process"
import { chmod, mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { promisify } from "node:util"

import { generateKeyPairSync } from "../../src/KeyGeneration.js"
import KnownHosts, { KnownHostsError } from "../../src/KnownHosts.js"
import PublicKey from "../../src/utils/PublicKey.js"

const execFileAsync = promisify(execFile)

describe("known hosts", () => {
    test("matches literal, wildcard, negated, changed, and revoked entries", () => {
        const trusted = generateKeyPairSync("ed25519").publicKey
        const replacement = generateKeyPairSync("ed25519").publicKey
        const revoked = generateKeyPairSync("ed25519").publicKey
        const knownHosts = KnownHosts.parse(`
# deployment hosts
*.example.test,!excluded.example.test ${trusted.data.alg} ${trusted.serialize().toString("base64")}
@revoked revoked.example.test ${revoked.data.alg} ${revoked.serialize().toString("base64")}
`)

        expect(knownHosts.check("api.example.test", trusted).status).toBe("trusted")
        expect(knownHosts.check("API.EXAMPLE.TEST", trusted).status).toBe("trusted")
        expect(knownHosts.check("api.example.test", replacement).status).toBe("changed")
        expect(knownHosts.check("excluded.example.test", trusted).status).toBe("unknown")
        expect(knownHosts.check("revoked.example.test", revoked)).toMatchObject({
            status: "revoked",
            line: 4,
        })
        expect(knownHosts.check("elsewhere.test", trusted).status).toBe("unknown")

        const nonDefault = KnownHosts.parse(`[port.example.test]:2222 ${trusted.toString()}`)
        expect(nonDefault.check("port.example.test", trusted, 2222).status).toBe("trusted")
        expect(nonDefault.check("port.example.test", trusted).status).toBe("unknown")
    })

    test("matches wildcard bytes with ASCII-only case folding and bounded work", () => {
        const key = generateKeyPairSync("ed25519").publicKey
        const oneByte = KnownHosts.parse(`caf? ${key.toString()}`)
        const twoBytes = KnownHosts.parse(`caf?? ${key.toString()}`)

        expect(oneByte.check("café", key).status).toBe("unknown")
        expect(twoBytes.check("café", key).status).toBe("trusted")
        expect(KnownHosts.parse(`Ä.example ${key}`).check("ä.example", key).status).toBe("unknown")
        const adversarial = KnownHosts.parse(`${"*a".repeat(500)}b ${key}`)
        expect(adversarial.check("a".repeat(1000), key).status).toBe("unknown")
    })

    test("agrees with the command-line wildcard matcher for multibyte hostnames", async () => {
        const directory = await mkdtemp(join(tmpdir(), "modernssh-known-host-pattern-"))
        try {
            const path = join(directory, "known_hosts")
            const key = generateKeyPairSync("ed25519").publicKey
            await writeFile(path, `caf? ${key}\ncaf?? ${key}\n`)

            const { stdout } = await execFileAsync("ssh-keygen", ["-F", "café", "-f", path])
            const matchedEntries = stdout
                .split("\n")
                .filter((line) => line.length > 0 && !line.startsWith("#"))
            expect(matchedEntries).toEqual([`caf?? ${key}`])
            expect(KnownHosts.parse(await readFile(path)).check("café", key).status).toBe("trusted")
        } finally {
            await rm(directory, { recursive: true, force: true })
        }
    })

    test("reads host hashes generated by ssh-keygen", async () => {
        const directory = await mkdtemp(join(tmpdir(), "modernssh-known-host-hash-"))
        try {
            const path = join(directory, "known_hosts")
            const key = generateKeyPairSync("ed25519").publicKey
            await writeFile(path, `hash.example.test ${key.toString()}\n`)
            await execFileAsync("ssh-keygen", ["-q", "-H", "-f", path])

            const content = await readFile(path, "utf8")
            expect(content).toStartWith("|1|")
            const knownHosts = await KnownHosts.load(path)
            expect(knownHosts.check("hash.example.test", key).status).toBe("trusted")
            expect(knownHosts.check("other.example.test", key).status).toBe("unknown")
        } finally {
            await rm(directory, { recursive: true, force: true })
        }
    })

    test("replaces exact host keys atomically while preserving policy and other hosts", async () => {
        const directory = await mkdtemp(join(tmpdir(), "modernssh-known-host-write-"))
        try {
            const path = join(directory, "known_hosts")
            const oldKey = generateKeyPairSync("ed25519").publicKey
            const newKey = generateKeyPairSync("ecdsa", { bits: 256 }).publicKey
            const revokedKey = generateKeyPairSync("ed25519").publicKey
            await writeFile(
                path,
                [
                    "# managed and policy entries",
                    `rotate.example.test,keep.example.test ${oldKey.toString()}`,
                    `*.example.test ${oldKey.toString()}`,
                    `@revoked rotate.example.test ${revokedKey.toString()}`,
                    "",
                ].join("\n"),
            )
            await chmod(path, 0o640)

            const knownHosts = await KnownHosts.load(path)
            await knownHosts.replaceHostKeys("rotate.example.test", [newKey], {
                hashHostname: true,
            })

            const content = await readFile(path, "utf8")
            expect(content).toContain(`keep.example.test ${oldKey.toString()}`)
            expect(content).toContain(`*.example.test ${oldKey.toString()}`)
            expect(content).toContain(`@revoked rotate.example.test ${revokedKey.toString()}`)
            expect(content).not.toContain(`rotate.example.test,keep.example.test`)
            expect(content).toContain("\n|1|")
            expect((await stat(path)).mode & 0o777).toBe(0o640)
            expect(knownHosts.check("rotate.example.test", newKey).status).toBe("trusted")

            const { stdout } = await execFileAsync("ssh-keygen", [
                "-F",
                "rotate.example.test",
                "-f",
                path,
            ])
            expect(stdout).toContain(newKey.serialize().toString("base64"))
        } finally {
            await rm(directory, { recursive: true, force: true })
        }
    })

    test("owns replacement inputs before the serialized update runs", async () => {
        const original = generateKeyPairSync("ed25519", {
            comment: "original@example.test",
        }).publicKey
        const replacement = generateKeyPairSync("ed25519").publicKey
        const encoded = Buffer.from(original.toString())
        const keys: (PublicKey | string | Buffer)[] = [encoded]
        const options = { port: 2222, hashHostname: false }
        const knownHosts = KnownHosts.parse("")

        const update = knownHosts.replaceHostKeys("owned.example.test", keys, options)
        encoded.fill(0)
        keys[0] = replacement
        options.port = 2200
        options.hashHostname = true
        await update

        expect(knownHosts.check("owned.example.test", original, 2222).status).toBe("trusted")
        expect(knownHosts.check("owned.example.test", replacement, 2222).status).toBe("changed")
        expect(knownHosts.check("owned.example.test", original, 2200).status).toBe("unknown")
        expect(knownHosts.toString()).toContain(" original@example.test\n")
    })

    test("validates replacement collections and options before queueing", async () => {
        const knownHosts = KnownHosts.parse("")
        await expect(
            knownHosts.replaceHostKeys("host.example.test", null as never),
        ).rejects.toThrow("keys must be an array")
        await expect(
            knownHosts.replaceHostKeys("host.example.test", [], null as never),
        ).rejects.toThrow("options must be an object")
        await expect(
            knownHosts.replaceHostKeys("host.example.test", [], {
                hashHostname: "yes" as never,
            }),
        ).rejects.toThrow("hashHostname option must be a boolean")
    })

    test("validates host certificates against matching authority entries", async () => {
        const directory = await mkdtemp(join(tmpdir(), "modernssh-known-host-ca-"))
        try {
            const authorityPath = join(directory, "authority")
            const hostPath = join(directory, "host")
            await execFileAsync("ssh-keygen", [
                "-q",
                "-t",
                "ed25519",
                "-N",
                "",
                "-f",
                authorityPath,
            ])
            await execFileAsync("ssh-keygen", ["-q", "-t", "ed25519", "-N", "", "-f", hostPath])
            await execFileAsync("ssh-keygen", [
                "-q",
                "-s",
                authorityPath,
                "-I",
                "host-certificate",
                "-h",
                "-n",
                "server.example.test",
                "-V",
                "-1m:+1h",
                `${hostPath}.pub`,
            ])

            const authority = PublicKey.parseString(await readFile(`${authorityPath}.pub`, "utf8"))
            const certificate = PublicKey.parseString(
                await readFile(`${hostPath}-cert.pub`, "utf8"),
            )
            const authorityLine = `@cert-authority *.example.test ${authority.toString()}`
            const knownHosts = KnownHosts.parse(authorityLine)

            expect(knownHosts.check("server.example.test", certificate).status).toBe("trusted")
            expect(knownHosts.check("other.example.test", certificate).status).toBe("changed")
            expect(
                KnownHosts.parse(
                    `@revoked *.example.test ${authority.toString()}\n${authorityLine}`,
                ).check("server.example.test", certificate).status,
            ).toBe("revoked")
        } finally {
            await rm(directory, { recursive: true, force: true })
        }
    })

    test("asserts trusted raw and parsed keys and rejects malformed files", () => {
        const key = generateKeyPairSync("ed25519").publicKey
        const knownHosts = KnownHosts.parse(`verify.example.test ${key.toString()}`)

        expect(knownHosts.assertTrusted("verify.example.test", key)).toBeUndefined()
        expect(knownHosts.assertTrusted("verify.example.test", key.serialize())).toBeUndefined()
        expect(() => knownHosts.assertTrusted("verify.example.test", "key" as never)).toThrow(
            "Known-host key must be a PublicKey or buffer",
        )
        const trustedController = { allowHostKey: false }
        const trustedHook = knownHosts.hostKeyHook("verify.example.test")
        let trustedStopped = false
        trustedHook({ stopPropagation: () => (trustedStopped = true) }, trustedController, key)
        expect(trustedStopped).toBe(false)
        expect(trustedController.allowHostKey).toBe(true)

        let stopped = false
        const deniedController: { allowHostKey: boolean; rejection?: Error } = {
            allowHostKey: true,
        }
        const deniedHook = knownHosts.hostKeyHook("missing.example.test")
        deniedHook({ stopPropagation: () => (stopped = true) }, deniedController, key)
        expect(stopped).toBe(true)
        expect(deniedController.allowHostKey).toBe(false)
        expect(deniedController.rejection).toBeInstanceOf(KnownHostsError)
        expect((deniedController.rejection as KnownHostsError).status).toBe("unknown")
        try {
            KnownHosts.parse(`other.example.test ${key.toString()}`).assertTrusted(
                "verify.example.test",
                key,
            )
            throw new Error("Expected verification to fail")
        } catch (error) {
            expect(error).toBeInstanceOf(KnownHostsError)
            expect((error as KnownHostsError).status).toBe("unknown")
        }

        expect(() => KnownHosts.parse("@unsupported host ssh-ed25519 AAAA")).toThrow(
            "Unsupported known-hosts marker",
        )
        expect(() =>
            KnownHosts.parse(
                `host,|1|AAAAAAAAAAAAAAAAAAAAAAAAAAA=|AAAAAAAAAAAAAAAAAAAAAAAAAAA= ${key.toString()}`,
            ),
        ).toThrow("only pattern")
        expect(() => KnownHosts.parse(`host ${key.data.alg} !!!!`)).toThrow("key encoding")
        expect(() =>
            KnownHosts.parse(`host ssh-rsa ${key.serialize().toString("base64")}`),
        ).toThrow("key type mismatch")
        const truncated = key.serialize().subarray(0, -1)
        expect(() =>
            KnownHosts.parse(`host ${key.data.alg} ${truncated.toString("base64")}`),
        ).toThrow("Invalid known-hosts key")
        expect(() => KnownHosts.parse(Buffer.from([0xff]))).toThrow("not valid UTF-8")
        expect(() => KnownHosts.parse(`host\r${key.toString()}`)).toThrow("bare carriage return")
        expect(() => KnownHosts.parse(`${"a".repeat(1024)} ${key}`)).toThrow(
            "pattern exceeds 1023 bytes",
        )
        expect(() => KnownHosts.parse("x".repeat(64 * 1024 + 1))).toThrow(
            "line 1 exceeds the maximum length",
        )
        expect(() => knownHosts.check("x".repeat(1024), key)).toThrow("hostname exceeds 1023 bytes")
        expect(() => new KnownHostsError({ status: "trusted" }, "trusted.example.test")).toThrow(
            "not an error",
        )
    })
})
