import { execFile } from "node:child_process"
import { mkdtemp, readFile, rm } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { promisify } from "node:util"
import DiskAgent from "../../src/publickey/DiskAgent.js"
import PrivateKey from "../../src/utils/PrivateKey.js"
import PublicKey from "../../src/utils/PublicKey.js"

const execFileAsync = promisify(execFile)
const passphrase = "correct horse battery staple"
const ciphers = [
    "3des-cbc",
    "aes128-cbc",
    "aes192-cbc",
    "aes256-cbc",
    "aes128-ctr",
    "aes192-ctr",
    "aes256-ctr",
    "aes128-gcm@openssh.com",
    "aes256-gcm@openssh.com",
    "chacha20-poly1305@openssh.com",
]

async function generateKey(
    directory: string,
    name: string,
    type: "ed25519" | "rsa",
    cipher = "aes256-ctr",
    keyPassphrase = passphrase,
): Promise<{ privateKey: string; publicKey: PublicKey }> {
    const keyPath = join(directory, name)
    await execFileAsync("ssh-keygen", [
        "-q",
        "-t",
        type,
        ...(type === "rsa" ? ["-b", "2048"] : []),
        "-N",
        keyPassphrase,
        "-C",
        name,
        "-a",
        "1",
        "-Z",
        cipher,
        "-f",
        keyPath,
    ])
    return {
        privateKey: await readFile(keyPath, "utf8"),
        publicKey: PublicKey.parseString(await readFile(`${keyPath}.pub`, "utf8")),
    }
}

function tamperWithAuthenticationTag(privateKey: string): string {
    const lines = privateKey.trim().split(/\r?\n/)
    const raw = Buffer.from(lines.slice(1, -1).join(""), "base64")
    raw[raw.length - 1] ^= 0x01
    const encoded = raw.toString("base64").match(/.{1,70}/g) ?? []
    return [lines[0], ...encoded, lines[lines.length - 1]].join("\n")
}

describe("OpenSSH private keys", () => {
    test("continues to parse an unencrypted key generated by OpenSSH", async () => {
        const directory = await mkdtemp(join(tmpdir(), "modernssh-unencrypted-private-key-"))
        try {
            const fixture = await generateKey(directory, "id_ed25519", "ed25519", "aes256-ctr", "")
            const privateKey = PrivateKey.fromString(fixture.privateKey)
            const data = Buffer.from("signed using an unencrypted OpenSSH key")

            expect(privateKey.data.publicKey.equals(fixture.publicKey)).toBe(true)
            expect(fixture.publicKey.verifySignature(data, privateKey.sign(data))).toBe(true)
        } finally {
            await rm(directory, { recursive: true, force: true })
        }
    })

    test("decrypts and signs with every cipher accepted by OpenSSH", async () => {
        const directory = await mkdtemp(join(tmpdir(), "modernssh-private-key-ciphers-"))
        try {
            for (const cipher of ciphers) {
                const fixture = await generateKey(directory, cipher, "ed25519", cipher)
                const privateKey = PrivateKey.fromString(fixture.privateKey, passphrase)
                const data = Buffer.from(`signed using ${cipher}`)

                expect(privateKey.data.comment).toBe(cipher)
                expect(privateKey.data.publicKey.equals(fixture.publicKey)).toBe(true)
                expect(fixture.publicKey.verifySignature(data, privateKey.sign(data))).toBe(true)
            }
        } finally {
            await rm(directory, { recursive: true, force: true })
        }
    }, 30_000)

    test("decrypts and signs an OpenSSH RSA key", async () => {
        const directory = await mkdtemp(join(tmpdir(), "modernssh-private-key-rsa-"))
        try {
            const fixture = await generateKey(directory, "id_rsa", "rsa")
            const privateKey = PrivateKey.fromString(fixture.privateKey, Buffer.from(passphrase))
            const data = Buffer.from("signed using an encrypted OpenSSH RSA key")

            expect(privateKey.data.publicKey.equals(fixture.publicKey)).toBe(true)
            expect(fixture.publicKey.verifySignature(data, privateKey.sign(data))).toBe(true)
        } finally {
            await rm(directory, { recursive: true, force: true })
        }
    }, 15_000)

    test("rejects missing and incorrect passphrases", async () => {
        const directory = await mkdtemp(join(tmpdir(), "modernssh-private-key-passphrase-"))
        try {
            const fixture = await generateKey(directory, "id_ed25519", "ed25519")

            expect(() => PrivateKey.fromString(fixture.privateKey)).toThrow("requires a passphrase")
            expect(() => PrivateKey.fromString(fixture.privateKey, "incorrect")).toThrow(
                /integrity|passphrase/i,
            )
        } finally {
            await rm(directory, { recursive: true, force: true })
        }
    })

    test("rejects tampering with authenticated OpenSSH key data", async () => {
        const directory = await mkdtemp(join(tmpdir(), "modernssh-private-key-tamper-"))
        try {
            const fixture = await generateKey(
                directory,
                "id_ed25519",
                "ed25519",
                "aes256-gcm@openssh.com",
            )
            const tampered = tamperWithAuthenticationTag(fixture.privateKey)

            expect(() => PrivateKey.fromString(tampered, passphrase)).toThrow()
        } finally {
            await rm(directory, { recursive: true, force: true })
        }
    })

    test("lets DiskAgent resolve a passphrase for an encrypted key", async () => {
        const directory = await mkdtemp(join(tmpdir(), "modernssh-encrypted-disk-agent-"))
        try {
            const fixture = await generateKey(directory, "id_ed25519", "ed25519")
            const keyPath = join(directory, "id_ed25519")
            const requestedPaths: string[] = []
            const agent = new DiskAgent(directory, {
                passphrase(path) {
                    requestedPaths.push(path)
                    return passphrase
                },
            })
            const data = Buffer.from("signed using DiskAgent")
            const signature = await agent.sign(keyPath, data)

            expect(requestedPaths).toEqual([keyPath])
            expect(fixture.publicKey.verifySignature(data, signature)).toBe(true)
        } finally {
            await rm(directory, { recursive: true, force: true })
        }
    })
})
